export const INTEGER = {
  APP_BAR_MOBILE: 56,
  APP_BAR_DESKTOP: 64,
  DRAWER_WIDTH: 290,

  //ROOM STATUS
  ROOM_EMPTY: 1,
  ROOM_PENDING: 2,
  ROOM_RENTED: 3,
};

export const STRING = {
  // User action types
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP",
  LOG_OUT: "LOG_OUT",
  GET_INFO: "GET_INFO",

  // Hotel action types
  CREATE_HOTEL: "CREATE_HOTEL",
  UPDATE_HOTEL: "UPDATE_HOTEL",
  DELETE_HOTEL: "DELETE_HOTEL",
  GET_ALL_HOTEL: "GET_ALL_HOTEL",

  // Room action types
  CREATE_ROOM: "CREATE_ROOM",
  UPDATE_ROOM: "UPDATE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  GET_ALL_ROOM: "GET_ALL_ROOM",

  // Room Service action types
  CREATE_ROOM_SERVICE: "CREATE_ROOM_SERVICE",
  UPDATE_ROOM_SERVICE: "UPDATE_ROOM_SERVICE",
  DELETE_ROOM_SERVICE: "DELETE_ROOM_SERVICE",
  GET_ALL_ROOM_SERVICE: "GET_ALL_ROOM_SERVICE",

  // Room type action types
  CREATE_ROOM_TYPE: "CREATE_ROOM_TYPE",
  UPDATE_ROOM_TYPE: "UPDATE_ROOM_TYPE",
  DELETE_ROOM_TYPE: "DELETE_ROOM_TYPE",
  GET_ALL_ROOM_TYPE: "GET_ALL_ROOM_TYPE",

  LOCAL_STORAGE_PROFILE_KEY:
    "065211f7a119d769f567ae067eb75951714d6a1df57bc30ff695befaed27059a613c76bdebf98e6d9700d4db50a99f7c",
};
